### ISSUE TITLE
W3C developers landing page: features & projects wishlist

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/modern-tooling#33]
The [developers landing page](http://w3c.github.io/developer-tools/) aims to provide to developers a complete list of all Open Source Projects at W3C. That page will also link to a donation program which will help us to get the funding to create awesome tools for developers.

Why not implement a wishlist for new features where developers can vote for their favorite project or propose a new one? We can also display a progress bar to show if we get enough donations to start a new project required by the community.

So far, I can think about 2 possibilities:
- use github issues as a wishlist (but no progress bar)
- or create a backend side to the platform like for the [Gitlab Open Source Project wishlist](http://feedback.gitlab.com/forums/176466-general)

The second option will probably be nicer but will require more time to be implemented.

**Comment by darobin** [comment]
It's a good idea. I think we should start small and simple, and see how it grows. My suggestion would be to begin with a list of issues on the repository for the landing page itself, simply with a link from the page to it and a blurb explaining it. I would suggest that we don't tie implementation to donation funding. There are cases in which we might decide to do something even if it isn't funded but simply because it's a god idea. Conversely, there could be a case in which a community manages to raise funds for a project we think would be detrimental to the Web or the organisation. In other words, donations are great but I am not sure we should be driven by them.

I would also suggest that the landing page be focused on listing resources for developers but not necessarily on listing our open source projects. The overlap is high, but we could list things there that aren't open source (and some might even be for pay); conversely some of the open source stuff we do is probably of no interest to developers (e.g. Echidna, Amaya).

I don't think the report needs to add anything here (but feel free to reopen the issue if you do). I suggest opening an issue on the landing page to handle this (or just doing it :).
