### ISSUE TITLE
CG tools for WGs

### ISSUE THREAD

**Issue by rigow** [w3c/modern-tooling#45]
I'm flabbergasted by the quality of tools for community groups. Working Groups have nothing comparable. Can we use the CG toolbox in a WG context. (feed syndication, dashboard etc)

**Comment by marcoscaceres** [comment]
we should look at if people actually use the CG tools tho (my suspicion is that they only get used a few times and then abandoned). In a few groups, ended up making our own tools/pages: 
- http://responsiveimages.org/
- http://ricg.io/ 
- http://webdevdata.org/

And the same for WG ... well, IG:  
- http://www.w3.org/Mobile/IG/

**Comment by darobin** [comment]
Most CG tools don't even get used once. I'm not sure what you find so great about them?

**Comment by rigow** [comment]
Do you have any data on CG tools not even being used once? This would indicate a terrible waste of time and resources. This is surely a topic for woods. But it needs evidence. Marcos, note that 3 Groups out of 199 have used their own tools. That means 196 CGs were satisfied with the existing tools. New tools means using more W3C resources that can't be used elsewhere. Such tradeoff has to be quantified IMHO.

**Comment by marcoscaceres** [comment]
On Sunday, April 19, 2015, Rigo Wenning notifications@github.com wrote:

> Do you have any data on CG tools not even being used once?
> 
> Just open random groups. There are not that many and most are dead.
> 
>  This would indicate a terrible waste of time and resources. This is
> surely a topic for woods. But it needs evidence. Marcos, note that 3 Groups
> out of 199 have used their own tools. That means 196 CGs were satisfied
> with the existing tools.
> 
> Heh, no :) most (~95%) CGs die a day or two after they start. So it's not
> accurate to say they are satisfied.

This is not to say we should kill CGs, just that they fail fast and cheap
(a good thing).

**Comment by darobin** [comment]
I haven't compiled data, but judging from the CGs I've been in:
- The wiki is almost never used. In fact none of the CGs I've been in has ever used its wiki that I know of. We stopped providing wikis by default because of this. There are still something like 180 wikis that were created automatically but have no content whatsoever
- The blog is rarely used. The vast majority of CGs have only the first test post (which is generated automatically). A smaller number may have made one or two posts thereafter, before giving up because, well, you don't need a blog, really.
- Mailing lists and the attendant archives do get used. We used to create way too many though (I don't know if that's still the case).
- The IP tools get used by successful CGs — but those are rare. They're good, though.
- The chair-picking tool tends to get used, if only because it's often the first thing that the people creating a CG do. But it is rarely revisited.

Are there other tools? I think we can summarise by saying:
- Failed CGs use the mailing list and perhaps the chair tool before dying.
- Successful CGs use the mailing list, the chair tool (once), GitHub, and in some cases an IRC channel they create. A handful of really successful ones use the IP tool.

CGs are great for getting an environment up quickly, but in terms of tooling I don't see them having anything particularly great.

**Comment by rigow** [comment]
So you have looked into the tooling already and you have considered it. That's what I wanted. Thanks for answering my issue

**Comment by AFBarstow** [comment]
So, a conclusion I'm getting then is that other than mail list support, the types of tools/services/features provided by Github (or similar) is sufficient for most if not all CGs. And probably true for most WGs too (although I loves me some IRC).

**Comment by rigow** [comment]
Art, 
and probably true for life, the universe and everything. Looks like Github really found what 42 means for Devs. We can probably close W3C and all move to Github. I don't think I want to stand in the way of that stampede. (sent from my spaceship with improbability drive)
